import Head from "next/head";
import styles from "@/styles/homestay/homestay.module.css";
import Header from "@/components/homestay/header";
import BoxSearch from "@/components/header/boxSearch";
import HomestayItem from "@/components/homestay/homestayItem";
import HomestayRecentItem from "@/components/homestay/homestayRecentItem";
import SearchHomeStay from "@/components/header/box_search/search_homestay";
import Footer from "@/components/footer/footer";
import { Col, Row } from "antd";
import { useState } from "react";
import Link from "next/link";
export default function Home() {
  const [activeMenu, setActiveMenu] = useState("ks"); //Bien gan gia tri cho phan menu tren thanh search
  //Su kien click vao item menu search
  const clickMenu = (e, active) => {
    setActiveMenu(active);
  };
  const list = [
    1, 2, 3, 4, 5, 6, 6, 2, 3, 4, 5, 2, 4, 2, 1, 2, 3, 5, 6, 1, 2, 3, 5, 7, 8,
    6, 8, 5, 3, 1,
  ];
  return (
    <>
      <Head>
        <title>Homestay</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header></Header>
      <div className={styles.banner_homestay}>
        <div className={`${styles.box_banner}`}>
          <div className={`${styles.banner_wrap}`}>
            <div className={styles.box_txt}>Tìm Homestay với Hunghabay</div>

            <div className={`${styles.box_search}`}>
              <div className={`${styles.box_top}`}>
                <div className={`${styles.box_menu}`}>
                  <div
                    className={`${styles.menu_item} ${
                      activeMenu == "ks" ? styles.menu_active : ""
                    }`}
                    onClick={(e) => clickMenu(e, "ks")}
                  >
                    Khách sạn
                  </div>
                  <div
                    className={`${styles.menu_item} ${
                      activeMenu == "nh" ? styles.menu_active : ""
                    }`}
                    onClick={(e) => clickMenu(e, "nh")}
                  >
                    Nhà hàng
                  </div>
                  <div
                    className={`${styles.menu_item} ${
                      activeMenu == "cb" ? styles.menu_active : ""
                    }`}
                    onClick={(e) => clickMenu(e, "cb")}
                  >
                    Chuyến bay
                  </div>
                  <div
                    className={`${styles.menu_item} ${
                      activeMenu == "ht" ? styles.menu_active : ""
                    }`}
                    onClick={(e) => clickMenu(e, "ht")}
                  >
                    Homestay
                  </div>
                </div>
                <div className={`${styles.map}`}>
                  <div className={`img_dl ${styles.img_map}`}>
                    <img src="/images/header/icon_map.svg" alt="Icon" />
                  </div>
                  <span className={`${styles.text_map}`}>Mở bản đồ</span>
                </div>
              </div>
              <SearchHomeStay></SearchHomeStay>
            </div>
          </div>
        </div>
      </div>
      {/* <div className={styles.list_homestay} >
                <h3>Homestay theo địa điểm</h3>
            </div> */}

      <div className={styles.list_homestay}>
        <h3>Homestay mới nhất</h3>
        <Row gutter={[24, 24]}>
          <Col span={8}>
            <HomestayItem />
          </Col>
          <Col span={8}>
            <HomestayItem />
          </Col>
          <Col span={8}>
            <HomestayItem />
          </Col>
        </Row>
        <Row gutter={[24, 24]}>
          <Col span={8}>
            <HomestayItem />
          </Col>
          <Col span={8}>
            <HomestayItem />
          </Col>
          <Col span={8}>
            <HomestayItem />
          </Col>
        </Row>
        <Row gutter={[24, 24]}>
          <Col span={8}>
            <HomestayItem />
          </Col>
          <Col span={8}>
            <HomestayItem />
          </Col>
          <Col span={8}>
            <HomestayItem />
          </Col>
        </Row>
        <div className={styles.btn_additional}>
          <button>
            Xem thêm{" "}
            <img src="/images/homestay/arrow-narrow-right.svg" alt="" />
          </button>
        </div>
      </div>
      <div className={styles.list_homestay_recent}>
        <h3>Xem gần đây</h3>
        <Row gutter={[16, 16]}>
          <Col span={6}>
            <HomestayRecentItem />
          </Col>
          <Col span={6}>
            <HomestayRecentItem />
          </Col>
          <Col span={6}>
            <HomestayRecentItem />
          </Col>
          <Col span={6}>
            <HomestayRecentItem />
          </Col>
        </Row>
      </div>
      <div className={styles.list_homestay_city}>
        <h3>Homestay theo tỉnh, thành phố</h3>
        <div className={styles.list}>
          {list?.map((item, key) => (
            <Link key={key} href={"#"} className={styles.item}>
              Hà Nội
            </Link>
          ))}
        </div>
      </div>

      <Footer></Footer>
    </>
  );
}
