import Head from "next/head";
import styles from "@/styles/homestay/homestay_search.module.css";
import style from '@/styles/header/box_search.module.css';
import Header from "@/components/homestay/header";
import BoxSearch from "@/components/header/boxSearch";
import HomestayItem from "@/components/homestay/homestayItem";
import HomestayRecentItem from "@/components/homestay/homestayRecentItem";
import ListNearRestaurant from "@/components/homestay/list_restaurant";
import SearchHomeStay from "@/components/header/box_search/search_homestay";
import Footer from "@/components/footer/footer";
import { Col, Row, Pagination } from 'antd';
export default function Home() {
    return (
        <>
            <Head>
                <title>Search</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Header ></Header>
            <div className={`${style.box_banner}`}>
                <div className={`${style.banner_wrap}`}>
                    {/* {activeMenu == 'ht' ?
                    <div className={styles.box_txt}>Tìm Homestay với Hunghabay</div> : */}


                    <div className={`${style.box_search}`}>
                        <SearchHomeStay></SearchHomeStay>
                    </div>
                </div>


            </div>

            <div className={styles.list_homestay}>
                <h3>Homestay tại Hà Nội</h3>

                {/* <Pagination defaultCurrent={1} total={50} /> */}
            </div>
            <div className={styles.list_homestay_city} >
                <h3>Nhà hàng xung quanh Homestay</h3>
                <Row gutter={[12, 12]} >
                    <Col span={4}><ListNearRestaurant /></Col>
                    <Col span={4}><ListNearRestaurant /></Col>
                    <Col span={4}><ListNearRestaurant /></Col>
                    <Col span={4}><ListNearRestaurant /></Col>
                    <Col span={4}><ListNearRestaurant /></Col>
                    <Col span={4}><ListNearRestaurant /></Col>
                </Row>
            </div>
            <div className={styles.list_homestay_recent} >
                <h3>Xem gần đây</h3>
                <Row gutter={[16, 16]} >
                    <Col span={6}><HomestayRecentItem /></Col>
                    <Col span={6}><HomestayRecentItem /></Col>
                    <Col span={6}><HomestayRecentItem /></Col>
                    <Col span={6}><HomestayRecentItem /></Col>
                </Row>
            </div>



            <Footer></Footer>
        </>
    );
}
