
'use client'

import Head from "next/head";
import Link from "next/link";
import {useState} from 'react'
import Header from "@/components/header/header_2";
import BoxSearch from "@/components/header/box_search/search_restaurant";
import Footer from "@/components/footer/footer";
import RestaurantDetail from "@/components/restaurant/restaurantDetail"
import HelpfullItem from "@/components/restaurant/helpfullItem"
import Contact from "@/components/restaurant/contact"
import Evaluate from "@/components/restaurant/evaluate"

import styles from "@/styles/restaurant/detail.module.css";


export default function Detail(props) {

  const [seeMore, setSeeMore] = useState(false)


  const restaurantDetail = {
    id: 1,
    title: `The Shells Resort & Spa Phú Quốc`,
    imgSrc1: `/images/restaurant/img-detail1.png`,
    imgSrc2: `/images/restaurant/img-detail1.png`,
    imgSrc3: `/images/restaurant/img-detail2.png`,
    rating: 9.2,
    commentCount: 156,
    address1: `64, Trần Hưng Đạo`,
    address2: `Phú Quốc, Kiên Giang`,
    timeOpen: '',
    price: '50k - 650k',
    description: 'Đỗ xe và Wi-Fi luôn miễn phí, vì vậy quý khách có thể giữ liên lạc, đến và đi tùy ý. Nằm ở vị trí trung tâm tại Hải Châu của Đà Nẵng, chỗ nghỉ này đặt quý khách ở gần các điểm thu hút và tùy chọn ăn uống thú vị. Đừng rời đi trước khi ghé thăm The Marble Mountains nổi tiếng. Được xếp hạng 5 sao, chỗ nghỉ chất lượng cao này cho phép khách nghỉ sử dụng mát-xa, xông khô và bốn tắm nước nóng ngay trong khuôn viên.'
  }


  //foods
  const foods = Array.from({ length: 8 }, (_, index) => ({
    id: index + 1,
    title: `Combo Sliver`,
    srcImg:'/images/restaurant/food.png'
  }));

  return (
    <>
      <Head>
        <title>The Shells Resort & Spa Phú Quốc</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <>
        <Header></Header>

        <div className={styles.container}>
          <div className={styles.boxsearch}>
            <BoxSearch></BoxSearch>
          </div>
          <RestaurantDetail restaurantDetail={restaurantDetail}/>

          <div className={styles.section2}>
            <div>
              {/* tiên nghi */}
              <div>
                <p className={styles.helpfull}>Tiện nghi</p>
                <div className={styles.hfSection}>
                  <HelpfullItem  srcImg='/images/restaurant/cart.svg' text='Cửa hàng dụng cụ thể thao' />
                  <HelpfullItem  srcImg='/images/restaurant/wifi.svg' text='Free wifi' />
                  <HelpfullItem  srcImg='/images/restaurant/wifiless.svg' text='Internet có dây' />
                  <HelpfullItem  srcImg='/images/restaurant/wifiless.svg' text='Internet có dây' />
                  <HelpfullItem  srcImg='/images/restaurant/wifiless.svg' text='Internet có dây' />
                  <HelpfullItem  srcImg='/images/restaurant/cart.svg' text='Cửa hàng dụng cụ thể thao' />
                  <HelpfullItem  srcImg='/images/restaurant/other.svg' text='Khác' />
                  <HelpfullItem  srcImg='/images/restaurant/wifiless.svg' text='Internet có dây' />
                  <HelpfullItem  srcImg='/images/restaurant/wifiless.svg' text='Internet có dây' />
                  <HelpfullItem  srcImg='/images/restaurant/cart.svg' text='12 tiện nghi' other={true}/>
                </div>
              </div>
              {/* chính sách */}
              <div>
                <p style={{marginTop:48}} className={styles.helpfull}>Chính sách</p>
                <div className={styles.policy}>
                  Bàn đặt của Quý khách sẽ được giữ tối đa đến giờ đã đặt, sau thời gian này nếu quý khách không đến và không thông báo bàn đặt tự động hủy mà không cần thông báo trước
                  <p>- Quý khách vui lòng thông báo cho Hunghabay.vn nếu điều chỉnh số lượng khách thực tế hoặc muốn hủy bàn đặt trước ít nhất 2 tiếng để được hỗ trợ.</p>
                  <p> - Toàn bộ chi phí phát sinh Quý khách vui lòng thỏa thuận và thanh toán với nhà hàng tại thời điểm sử dụng dịch vụ.</p>
                </div>
              </div>  
              {/* Menu nhà hàng */}
              <div>
                <p style={{marginTop:58}}  className={styles.helpfull}>Menu nhà hàng</p>
                <div className={styles.menu}>
                  <img src="/images/restaurant/menuimg1.png" alt="Icon_hh" /> 
                  <img src="/images/restaurant/menuimg2.png" alt="Icon_hh" /> 
                  <img src="/images/restaurant/menuimg2.png" alt="Icon_hh" /> 
                  <img src="/images/restaurant/menuimg2.png" alt="Icon_hh" /> 
                </div>
              </div>
              {/* Món ăn */}
              <div>
                <p style={{marginTop:48}}  className={styles.helpfull}>Món ăn (32)</p>
                <div className={styles.foods}>
                  {
                    foods?.map(food =>
                      (
                        <div key={food.id }>
                            <img src={food.srcImg} alt="icon" />
                            <p style={{marginTop:8}}>{food.title}</p>
                            <div style={{marginTop:8}}>
                            <span className={styles.food_}>
                              <img src='/images/restaurant/heart.svg' alt="icon" />
                              <span style={{marginLeft:8}}>Thích (12)</span>
                            </span>
                            </div>
                        </div>
                      )
                    )
                  }
                  {/* buttom xem thêm */}
                </div>
              </div>
              <p className={styles.seeMore}>Xem thêm </p>
            </div>
            <div> 
              <Contact/>
            </div>
          </div>
          <div>
            <Evaluate />
          </div>
        </div>
          <Footer/>
      </>
    </>
  )
}