import Footer from "@/components/footer/footer";
import HeaderOther from "@/components/header/header_other";
import ListCity from "@/components/hotel/list_city";
import ListHotel from "@/components/hotel/list_hotel";
import ListSuggest from "@/components/hotel/list_suggest";
import Head from "next/head";

export default function Hotel() {
  return (
    <>
      <Head>
        <title>Khách sạn</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HeaderOther active={1} />

      {/* Danh sach khach san moi nhat */}
      <ListHotel></ListHotel>

      {/* Danh sach xem gan day */}
      <ListSuggest />

      {/* Danh sach khach san tinh thanh pho */}
      <ListCity />

      <Footer></Footer>
    </>
  );
}
