import Head from "next/head";
import styles from "@/styles/Home.module.css";
import Header from "@/components/header/header";
import BoxSearch from "@/components/header/boxSearch";
import Slide from "@/components/home/slide";
import Slider from "react-slick";
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";
import ListHotel from "@/components/home/list_hotel";
import { useState } from "react";
import Link from "next/link";
import ListHomeStay from "@/components/home/list_homestay";
import ListRestaurant from "@/components/home/list_restaurant";
import FavoriteDestination from "@/components/home/favorite_destination";
import PopularFlightRoute from "@/components/home/popular_flight_route";
import ListBlog from "@/components/home/list_blog";
import Footer from "@/components/footer/footer";
export default function Home() {
  const [getShowKs, setShowKs] = useState(true); //Bien show khach san
  const [getShowHt, setShowHt] = useState(true); //Bien show homestay
  const [getShowNh, setShowNh] = useState(true); //Bien show nha hang

  return (
    <>
      <Head>
        <title>Trang chủ</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={`${styles.container}`}>
        <div className={`${styles.banner_home}`}>
          <Header></Header>
          <BoxSearch></BoxSearch>
        </div>
        {/* Slide trang chủ */}
        <Slide></Slide>

        {/* Danh sach khach san */}
        <div className={`${styles.list_news}`}>
          <div className={`${styles.hotel_top}`}>
            <div className={`${styles.hotel_top_txt}`}>Khách sạn</div>
            <div className={`${styles.hotel_top_item}`}>
              <div
                className={`${styles.hotel_item} ${
                  getShowKs ? styles.hotel_active : ""
                }`}
                onClick={(e) => {
                  setShowKs(true);
                }}
              >
                Được đề xuất
              </div>
              <div
                className={`${styles.hotel_item} ${
                  !getShowKs ? styles.hotel_active : ""
                }`}
                onClick={(e) => {
                  setShowKs(false);
                }}
              >
                Đánh giá cao
              </div>
            </div>
          </div>
          <div className={`${styles.slide_hotel}`}>
            <ListHotel></ListHotel>
          </div>
          <div className={`${styles.box_btn_xt}`}>
            <Link href="#" className={`${styles.btn_xt}`}>
              <span>Xem thêm</span>
              <div className={`img_dl ${styles.img_xt}`}>
                <img src="/images/home/icon_xt.svg" alt="Icon" />
              </div>
            </Link>
          </div>
        </div>

        {/* Danh sach homestay */}
        <div className={`${styles.list_news} ${styles.bgr_news}`}>
          <div className={`${styles.hotel_top}`}>
            <div className={`${styles.hotel_top_txt}`}>Homestay</div>
            <div className={`${styles.hotel_top_item}`}>
              <div
                className={`${styles.hotel_item} ${
                  getShowHt ? styles.hotel_active : ""
                }`}
                onClick={(e) => {
                  setShowHt(true);
                }}
              >
                Được đề xuất
              </div>
              <div
                className={`${styles.hotel_item} ${
                  !getShowHt ? styles.hotel_active : ""
                }`}
                onClick={(e) => {
                  setShowHt(false);
                }}
              >
                Đánh giá cao
              </div>
            </div>
          </div>
          <div className={`${styles.slide_hotel}`}>
            <ListHomeStay></ListHomeStay>
          </div>
          <div className={`${styles.box_btn_xt}`}>
            <Link href="#" className={`${styles.btn_xt}`}>
              <span>Xem thêm</span>
              <div className={`img_dl ${styles.img_xt}`}>
                <img src="/images/home/icon_xt.svg" alt="Icon" />
              </div>
            </Link>
          </div>
        </div>
        {/* Danh sach nha hang */}
        <div className={`${styles.list_news}`}>
          <div className={`${styles.hotel_top}`}>
            <div className={`${styles.hotel_top_txt}`}>Nhà hàng</div>
            <div className={`${styles.hotel_top_item}`}>
              <div
                className={`${styles.hotel_item} ${
                  getShowNh ? styles.hotel_active : ""
                }`}
                onClick={(e) => {
                  setShowNh(true);
                }}
              >
                Được đề xuất
              </div>
              <div
                className={`${styles.hotel_item} ${
                  !getShowNh ? styles.hotel_active : ""
                }`}
                onClick={(e) => {
                  setShowNh(false);
                }}
              >
                Đánh giá cao
              </div>
            </div>
          </div>
          <div className={`${styles.slide_hotel}`}>
            <ListRestaurant></ListRestaurant>
          </div>
          <div className={`${styles.box_btn_xt}`}>
            <Link href="#" className={`${styles.btn_xt}`}>
              <span>Xem thêm</span>
              <div className={`img_dl ${styles.img_xt}`}>
                <img src="/images/home/icon_xt.svg" alt="Icon" />
              </div>
            </Link>
          </div>
        </div>

        {/* Diem den yeu thich */}
        <FavoriteDestination></FavoriteDestination>
        <PopularFlightRoute></PopularFlightRoute>
        <ListBlog></ListBlog>

        <Footer></Footer>
      </div>
    </>
  );
}
