import Head from "next/head";
import styles from "@/styles/homestay/homestay.module.css";
import Header from "@/components/header/header";
import BoxSearch from "@/components/header/boxSearch";
import Slider from 'react-slick';
import HomestayItem from "@/components/homestay/homestayItem";
import HomestayRecentItem from "@/components/homestay/homestayRecentItem";
import { Col, Row } from 'antd';
import CarItem from "@/components/car/car_item";
import { useState } from "react";
import ListHomeStay from "@/components/home/list_homestay";
import Link from "next/link";
export default function Home() {
    const [getShowHt, setShowHt] = useState(true); //Bien show homestay

    return (
        <>
            <Head>
                <title>Car</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className={styles.banner_homestay}>
                <Header></Header>
                <BoxSearch></BoxSearch>

            </div>
            <div className={`${styles.list_news} ${styles.bgr_news}`}>
                <div className={`${styles.hotel_top}`}>
                    <div className={`${styles.hotel_top_txt}`}>
                        Thuê xe tự lái
                    </div>

                </div>
                <div className={`${styles.slide_hotel}`}>
                    <CarItem></CarItem>
                </div>
            </div>
            <div className={`${styles.list_news} ${styles.bgr_news}`}>
                <div className={`${styles.hotel_top}`}>
                    <div className={`${styles.hotel_top_txt}`}>
                        Xe nổi bật
                    </div>
                    <div className={`${styles.hotel_top_item}`}>
                        <div className={`${styles.hotel_item} ${getShowHt ? styles.hotel_active : ''}`} onClick={(e) => { setShowHt(true) }}>
                            1 chiều
                        </div>
                        <div className={`${styles.hotel_item} ${!getShowHt ? styles.hotel_active : ''}`} onClick={(e) => { setShowHt(false) }}>
                            2 chiều
                        </div>
                    </div>
                </div>
                <div className={`${styles.slide_hotel}`}>
                    <CarItem></CarItem>
                </div>
            </div>
        </>
    );
}
