import Head from "next/head";
import styles from "@/styles/tour/customer/home.module.css";
import Image from "next/image";
import { formatToVND } from "@/utils/funtions";
import SearchTour from "@/components/header/box_search/search_tour";
import Link from "next/link";

let listTour = [];
for (let index = 0; index < 20; index++) {
  listTour.push({
    name: "Tour 2N1Đ Hà Nội - Quảng Ninh: Hành Hương Yên Tử",
    address: "Yên Tử, Quảng Ninh",
    customer: 20,
    long: "2 Ngày 1 Đêm",
    price: formatToVND(13102000),
  });
}

export default function Home() {
  return (
    <>
      <Head>
        <title>List tour</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.home}>
        <div className={styles.banner}></div>
        <div className={styles.box_search}>
          <SearchTour></SearchTour>
        </div>
        <div className={styles.block_tour}>
          <p className={styles.block_tour_title}>Tour được đề xuất</p>
          <div className={styles.list_tour}>
            {listTour.map((tour, i) => (
              <Link className={styles.tour} key={i} href="">
                <div className={styles.block_img}>
                  <Image
                    layout="fill"
                    src="https://www.elle.vn/wp-content/uploads/2023/11/18/558197/Bach-Loc-vai-Tang-Tuu-trong-Truong-Nguyet-Tan-Minh.jpg"
                    alt="tour"
                  />
                </div>
                <div className="block_detail">
                  <p className={styles.tour_name}>{tour.name}</p>
                  <p className={styles.tour_address}>
                    <img src="/images/tour/icon_address.svg" alt="icon" />
                    <span>{tour.address}</span>
                  </p>
                  <div className={styles.block_subdetail}>
                    <div className={styles.tour_customer}>
                      <img src="/images/tour/icon_user.svg" alt="icon" />
                      <span>{tour.customer} hành khách</span>
                    </div>
                    <div className={styles.tour_long}>
                      <img src="/images/tour/icon_clock.svg" alt="icon" />
                      <span>{tour.long}</span>
                    </div>
                  </div>
                  <p className={styles.price}>
                    Từ <span>{tour.price}</span> / người
                  </p>
                </div>
              </Link>
            ))}
          </div>
        </div>
      </div>
    </>
  );
}
