import Head from "next/head";
import { useEffect, useState } from "react";
import styles from "@/styles/tour/customer/home.module.css";
import search from "@/styles/tour/customer/search.module.css";
import Image from "next/image";
import { formatToVND, getVehicleIconName } from "@/utils/funtions";
import SearchTour from "@/components/header/box_search/search_tour";
import Breadcrumb from "@/components/Breadcrumb";
import Header from "@/components/header/header";
import TwoPointRangeSlider from "@/components/TwoPointRangeSlider";
import Link from "next/link";

export default function Home() {
  // handle sort
  const [sort, getSort] = useState("propose");

  const chooseSort = (type) => {
    getSort(type);
  };

  const [expand, isExpand] = useState(true);

  // handle open/close filter
  const chooseExpand = () => {
    if (expand) {
      isExpand(false);
    } else {
      isExpand(true);
    }
  };

  const [expand1, isExpand1] = useState(true);

  const chooseExpand1 = () => {
    if (expand1) {
      isExpand1(false);
    } else {
      isExpand1(true);
    }
  };

  const [expand2, isExpand2] = useState(true);

  const chooseExpand2 = () => {
    if (expand2) {
      isExpand2(false);
    } else {
      isExpand2(true);
    }
  };

  // handle open/close filter on mobile
  const [isSmallScreen, setIsSmallScreen] = useState(false);

  useEffect(() => {
    setIsSmallScreen(window.innerWidth < 450);
    isExpand(!(window.innerWidth < 450));
    console.log(expand);
  }, []);

  const clickFilterMobi = () => {
    if (isSmallScreen) {
      chooseExpand();
    }
  };

  // handle list item
  const getArrVehicleIconName = (arrVehicle) => {
    let arrVehicleIconName = [];
    arrVehicle.forEach((item) => {
      arrVehicleIconName.push(getVehicleIconName(item));
    });
    return arrVehicleIconName;
  };

  let listTour = [];
  for (let index = 0; index < 20; index++) {
    listTour.push({
      name: "Tour 2N1Đ Hà Nội - Quảng Ninh: Hành Hương Yên Tử",
      address: "Yên Tử, Quảng Ninh",
      customer: 20,
      long: "2 Ngày 1 Đêm",
      price: formatToVND(13102000),
      vehicle: getArrVehicleIconName([1, 2, 4]),
      date: 123456789,
    });
  }

  // breadcrumb
  const breadcrumbItems = [
    {
      href: "/",
      text: "Trang chủ",
    },
    {
      href: "/tour/customer/home",
      text: "Tour",
    },
    {
      href: "/tour/customer/search",
      text: "Quảng Ninh",
    },
  ];

  return (
    <>
      <Head>
        <title>Tìm kiếm tour</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header></Header>
      <div className={styles.home}>
        <div className={search.box_search}>
          <SearchTour></SearchTour>
        </div>
        <div className={search.block_tour}>
          <Breadcrumb items={breadcrumbItems} className={search.breadcrumb} />
          <p className={search.block_tour_title}>Tour được đề xuất </p>
          <p className={search.count_tour}>156 tour</p>
          <div className={search.block_bottom}>
            <div className={search.block_filter}>
              <div
                className={search.block_filter_top}
                onClick={clickFilterMobi} // ???
              >
                <img src="/images/tour/icon_filter.svg" alt="icon" />
                <span>Bộ lọc</span>
              </div>
              <div
                className={search.block_filter_mid}
                style={{ display: expand ? "block" : "none" }}
              >
                <div
                  className={search.block_range_price}
                  style={{ paddingBottom: expand1 ? "60px" : "0" }}
                >
                  <div
                    className={` ${search.range_price_top} unselectable`}
                    onClick={chooseExpand1}
                  >
                    <div className={search.range_price_top1}>
                      <img src="/images/tour/icon_range_price.svg" alt="icon" />
                      <span>Khoảng giá</span>
                    </div>
                    <img
                      src={
                        expand1
                          ? "/images/tour/icon_arr_up.svg"
                          : "/images/tour/icon_arr_down.svg"
                      }
                      alt="icon"
                    />
                  </div>
                  <div style={{ display: expand1 ? "block" : "none" }}>
                    <TwoPointRangeSlider value={100000000} />
                  </div>
                </div>
                <div
                  className={search.block_type_tour}
                  style={{ paddingBottom: expand2 ? "30px" : "0" }}
                >
                  <div
                    className={` ${search.type_tour_top} unselectable`}
                    onClick={chooseExpand2}
                  >
                    <div className={search.type_tour_top1}>
                      <img src="/images/tour/icon_palette.svg" alt="icon" />
                      <span>Chủ đề tour</span>
                    </div>
                    <img
                      src={
                        expand2
                          ? "/images/tour/icon_arr_up.svg"
                          : "/images/tour/icon_arr_down.svg"
                      }
                      alt="icon"
                    />
                  </div>
                  <div
                    className={search.list_type_tour}
                    style={{ display: expand2 ? "flex" : "none" }}
                  >
                    <div className={search.type_tour}>
                      <input type="radio" id="1" name="tour" />
                      <label htmlFor="1">Tour nội địa cao cấp</label>
                    </div>
                    <div className={search.type_tour}>
                      <input type="radio" id="2" name="tour" />
                      <label htmlFor="2">Tour nội địa cao cấp</label>
                    </div>
                    <div className={search.type_tour}>
                      <input type="radio" id="3" name="tour" />
                      <label htmlFor="3">Tour nội địa cao cấp</label>
                    </div>
                  </div>
                </div>
              </div>
              <div className={search.block_filter_bottom}>
                <div
                  className={` ${search.block_expand} unselectable`}
                  style={{ display: expand ? "flex" : "none" }}
                  onClick={chooseExpand}
                >
                  <span>Thu gọn</span>
                  <img src="/images/tour/icon_arr_up_blue.svg" alt="icon" />
                </div>
                <div
                  className={` ${search.block_expand} unselectable`}
                  style={{ display: !expand ? "flex" : "none" }}
                  onClick={chooseExpand}
                >
                  <span>Mở rộng</span>
                  <img src="/images/tour/icon_arr_down_blue.svg" alt="icon" />
                </div>
              </div>
            </div>
            <div className={search.block_list_tour}>
              <div className={search.block_sort}>
                <button
                  className={`${search.sort} ${
                    sort == "propose" ? search.active_sort : ""
                  }`}
                  onClick={() => chooseSort("propose")}
                >
                  Đề xuất
                </button>
                <button
                  className={`${search.sort} ${
                    sort == "increase" ? search.active_sort : ""
                  }`}
                  onClick={() => chooseSort("increase")}
                >
                  Giá tăng dần
                </button>
                <button
                  className={`${search.sort} ${
                    sort == "decrease" ? search.active_sort : ""
                  }`}
                  onClick={() => chooseSort("decrease")}
                >
                  Giá giảm dần
                </button>
              </div>
              <div className={search.list_tour}>
                {listTour.map((tour, i) => (
                  <Link className={search.tour} key={i} href="">
                    <div className={search.block_img}>
                      <Image
                        layout="fill"
                        src="https://www.elle.vn/wp-content/uploads/2023/11/18/558197/Bach-Loc-vai-Tang-Tuu-trong-Truong-Nguyet-Tan-Minh.jpg"
                        alt="tour"
                      />
                    </div>
                    <div className={search.block_detail}>
                      <p className={styles.tour_name}>{tour.name}</p>
                      <p className={styles.tour_address}>
                        <img src="/images/tour/icon_address.svg" alt="icon" />
                        <span>{tour.address}</span>
                      </p>
                      <div className={search.block_subdetail}>
                        <div className={search.tour_customer}>
                          <img src="/images/tour/icon_user.svg" alt="icon" />
                          <span>{tour.customer} hành khách</span>
                        </div>
                        <div className={search.tour_long}>
                          <img src="/images/tour/icon_clock.svg" alt="icon" />
                          <span>{tour.long}</span>
                        </div>
                        <div className={search.vehicle}>
                          <span>Phương tiện</span>
                          {tour.vehicle.map((name, i) => (
                            <>
                              <img
                                src={`/images/tour/${name}.svg`}
                                alt="icon"
                              />
                            </>
                          ))}
                        </div>
                      </div>
                      <p className={search.time_start}>
                        Ngày khởi hành: 10/03/2022 - 16/03/2022
                      </p>
                      <p className={styles.price}>
                        Từ <span>{tour.price}</span> / người
                      </p>
                    </div>
                  </Link>
                ))}
              </div>
            </div>
          </div>
        </div>
      </div>
    </>
  );
}
